version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}-mysql
    networks:
      - backend
    environment:
      MYSQL_DATABASE: ${DB_NAME} 
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ../db_data/:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    depends_on:
      - mysql
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    networks:
      - backend
      - frontend
  wordpress:
    build: './wordpress/'
    container_name: ${APP_NAME}-wordpress
    depends_on:
      - mysql
    networks:
      - backend
      - frontend
    volumes:
      - ../project/:/var/www/html
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
# wp-admin: user@pass
networks:
  frontend:
  backend:
